<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYFEARQv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYFEARQv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYFEARQv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYFEARQv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYFEARQv\App_KernelDevDebugContainer([
    'container.build_hash' => 'YFEARQv',
    'container.build_id' => 'c5f7b555',
    'container.build_time' => 1781814094,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYFEARQv');
