<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQ8y_ZQService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.kQ8y.ZQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kQ8y.ZQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advert' => ['privates', '.errored..service_locator.kQ8y.ZQ.App\\Entity\\Advert', NULL, 'Cannot autowire service ".service_locator.kQ8y.ZQ": it needs an instance of "App\\Entity\\Advert" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'advert' => 'App\\Entity\\Advert',
        ]);
    }
}
