<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdvertController' shared autowired service.
     *
     * @return \App\Controller\AdvertController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdvertController.php';

        $container->services['App\\Controller\\AdvertController'] = $instance = new \App\Controller\AdvertController(($container->privates['App\\Service\\AdvertService'] ?? $container->load('getAdvertServiceService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['App\\Service\\CategoryService'] ?? $container->load('getCategoryServiceService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AdvertController', $container));

        return $instance;
    }
}
