<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertListInputFiltersDtoService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\AdvertListInputFiltersDto' shared autowired service.
     *
     * @return \App\Dto\AdvertListInputFiltersDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/AdvertListInputFiltersDto.php';

        return $container->privates['App\\Dto\\AdvertListInputFiltersDto'] = new \App\Dto\AdvertListInputFiltersDto();
    }
}
