<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertControllerindexService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.HZMB2Cd.App\Controller\AdvertController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZMB2Cd.App\\Controller\\AdvertController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', 'App\\Dto\\AdvertListInputFiltersDto', 'getAdvertListInputFiltersDtoService', true],
        ], [
            'filters' => 'App\\Dto\\AdvertListInputFiltersDto',
        ]))->withContext('App\\Controller\\AdvertController::index()', $container);
    }
}
