<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertListInputFiltersDtoResolver2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Resolver\AdvertListInputFiltersDtoResolver' shared autowired service.
     *
     * @return \App\Resolver\AdvertListInputFiltersDtoResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Resolver/AdvertListInputFiltersDtoResolver.php';

        return $container->privates['App\\Resolver\\AdvertListInputFiltersDtoResolver'] = new \App\Resolver\AdvertListInputFiltersDtoResolver();
    }
}
