<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\AdvertService' shared autowired service.
     *
     * @return \App\Service\AdvertService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AdvertServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AdvertService.php';

        return $container->privates['App\\Service\\AdvertService'] = new \App\Service\AdvertService(($container->privates['App\\Service\\CategoryService'] ?? $container->load('getCategoryServiceService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['App\\Service\\TagService'] ?? $container->load('getTagServiceService')), ($container->privates['App\\Repository\\AdvertRepository'] ?? $container->load('getAdvertRepositoryService')));
    }
}
