<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/FixturesProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Fixture.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AbstractBaseFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AdvertFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CategoryFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/TagFixtures.php';

        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader();

        $instance->addFixtures([['fixture' => ($container->privates['App\\DataFixtures\\AdvertFixtures'] ??= new \App\DataFixtures\AdvertFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\CategoryFixtures'] ??= new \App\DataFixtures\CategoryFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\TagFixtures'] ??= new \App\DataFixtures\TagFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\DataFixtures\\UserFixtures'] ?? $container->load('getUserFixturesService')), 'groups' => []]]);

        return $instance;
    }
}
