<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordChangeTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\PasswordChangeType' shared autowired service.
     *
     * @return \App\Form\Type\PasswordChangeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/PasswordChangeType.php';

        return $container->privates['App\\Form\\Type\\PasswordChangeType'] = new \App\Form\Type\PasswordChangeType(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
