<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagsDataTransformerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\DataTransformer\TagsDataTransformer' shared autowired service.
     *
     * @return \App\Form\DataTransformer\TagsDataTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DataTransformer/TagsDataTransformer.php';

        return $container->privates['App\\Form\\DataTransformer\\TagsDataTransformer'] = new \App\Form\DataTransformer\TagsDataTransformer(($container->privates['App\\Service\\TagService'] ?? $container->load('getTagServiceService')));
    }
}
