<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerdeleteService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.vHgnEho.App\Controller\TagController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vHgnEho.App\\Controller\\TagController::delete()'] = ($container->privates['.service_locator.vHgnEho'] ?? $container->load('get_ServiceLocator_VHgnEhoService'))->withContext('App\\Controller\\TagController::delete()', $container);
    }
}
