<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.App\Security\Voter\UserVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';

        $a = ($container->privates['App\\Security\\Voter\\UserVoter'] ?? $container->load('getUserVoter2Service'));

        if (isset($container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'])) {
            return $container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'])) {
            return $container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'];
        }

        $instance = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter($a, $b);

        if (isset($container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'])) {
            return $container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'];
        }

        return $container->privates['.debug.security.voter.App\\Security\\Voter\\UserVoter'] = $instance;
    }
}
