<?php

namespace ContainerUjhGlCG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserVoter2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\UserVoter' shared autowired service.
     *
     * @return \App\Security\Voter\UserVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/UserVoter.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Security\\Voter\\UserVoter'])) {
            return $container->privates['App\\Security\\Voter\\UserVoter'];
        }

        $instance = new \App\Security\Voter\UserVoter($a);

        if (isset($container->privates['App\\Security\\Voter\\UserVoter'])) {
            return $container->privates['App\\Security\\Voter\\UserVoter'];
        }

        return $container->privates['App\\Security\\Voter\\UserVoter'] = $instance;
    }
}
