<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjhGlCG\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjhGlCG/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUjhGlCG.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUjhGlCG\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerUjhGlCG\App_KernelTestDebugContainer([
    'container.build_hash' => 'UjhGlCG',
    'container.build_id' => '119c24fa',
    'container.build_time' => 1781387577,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjhGlCG');
