<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MDTFg_LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mDTFg.l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mDTFg.l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdvertController::index' => ['privates', '.service_locator.HZMB2Cd.App\\Controller\\AdvertController::index()', 'getAdvertControllerindexService', true],
            'App\\Controller\\AdvertController::show' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::show()', 'getAdvertControllershowService', true],
            'App\\Controller\\AdvertController::edit' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::edit()', 'getAdvertControllereditService', true],
            'App\\Controller\\AdvertController::delete' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::delete()', 'getAdvertControllerdeleteService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TagController::show' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::show()', 'getTagControllershowService', true],
            'App\\Controller\\TagController::edit' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::edit()', 'getTagControllereditService', true],
            'App\\Controller\\TagController::delete' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::delete()', 'getTagControllerdeleteService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdvertController:index' => ['privates', '.service_locator.HZMB2Cd.App\\Controller\\AdvertController::index()', 'getAdvertControllerindexService', true],
            'App\\Controller\\AdvertController:show' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::show()', 'getAdvertControllershowService', true],
            'App\\Controller\\AdvertController:edit' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::edit()', 'getAdvertControllereditService', true],
            'App\\Controller\\AdvertController:delete' => ['privates', '.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::delete()', 'getAdvertControllerdeleteService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.Cm49tF9.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TagController:show' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::show()', 'getTagControllershowService', true],
            'App\\Controller\\TagController:edit' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::edit()', 'getTagControllereditService', true],
            'App\\Controller\\TagController:delete' => ['privates', '.service_locator.vHgnEho.App\\Controller\\TagController::delete()', 'getTagControllerdeleteService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.kYAceIU.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdvertController::index' => '?',
            'App\\Controller\\AdvertController::show' => '?',
            'App\\Controller\\AdvertController::edit' => '?',
            'App\\Controller\\AdvertController::delete' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TagController::show' => '?',
            'App\\Controller\\TagController::edit' => '?',
            'App\\Controller\\TagController::delete' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdvertController:index' => '?',
            'App\\Controller\\AdvertController:show' => '?',
            'App\\Controller\\AdvertController:edit' => '?',
            'App\\Controller\\AdvertController:delete' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TagController:show' => '?',
            'App\\Controller\\TagController:edit' => '?',
            'App\\Controller\\TagController:delete' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
