<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kQ8y.ZQ.App\Entity\Advert' shared service.
     *
     * @return \App\Entity\Advert
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kQ8y.ZQ": it needs an instance of "App\\Entity\\Advert" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
