<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kQ8y.ZQ.App\Controller\AdvertController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kQ8y.ZQ.App\\Controller\\AdvertController::edit()'] = ($container->privates['.service_locator.kQ8y.ZQ'] ?? $container->load('get_ServiceLocator_KQ8y_ZQService'))->withContext('App\\Controller\\AdvertController::edit()', $container);
    }
}
