<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\AdvertType' shared autowired service.
     *
     * @return \App\Form\Type\AdvertType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/AdvertType.php';

        return $container->privates['App\\Form\\Type\\AdvertType'] = new \App\Form\Type\AdvertType(($container->privates['App\\Form\\DataTransformer\\TagsDataTransformer'] ?? $container->load('getTagsDataTransformerService')));
    }
}
