<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdvertController' shared autowired service.
     *
     * @return \App\Controller\AdvertController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdvertController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AdvertServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/AdvertService.php';

        $a = ($container->privates['App\\Service\\CategoryService'] ?? $container->load('getCategoryServiceService'));

        $container->services['App\\Controller\\AdvertController'] = $instance = new \App\Controller\AdvertController(new \App\Service\AdvertService($a, ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['App\\Service\\TagService'] ?? $container->load('getTagServiceService')), ($container->privates['App\\Repository\\AdvertRepository'] ?? $container->load('getAdvertRepositoryService'))), ($container->services['translator'] ?? self::getTranslatorService($container)), $a);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AdvertController', $container));

        return $instance;
    }
}
