<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\CategoryType' shared autowired service.
     *
     * @return \App\Form\Type\CategoryType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/CategoryType.php';

        return $container->privates['App\\Form\\Type\\CategoryType'] = new \App\Form\Type\CategoryType(($container->privates['App\\Form\\DataTransformer\\TagsDataTransformer'] ?? $container->load('getTagsDataTransformerService')));
    }
}
