<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CategoryService' shared autowired service.
     *
     * @return \App\Service\CategoryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryService.php';

        return $container->privates['App\\Service\\CategoryService'] = new \App\Service\CategoryService(($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Repository\\AdvertRepository'] ?? $container->load('getAdvertRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));
    }
}
