<?php

namespace ContainerYFEARQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TagService' shared autowired service.
     *
     * @return \App\Service\TagService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TagServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TagService.php';

        return $container->privates['App\\Service\\TagService'] = new \App\Service\TagService(($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));
    }
}
